export const initialValues = {
    nome: "",
    codigoInterno: "",
    grupo_produto_id: -1,
    unidade_produto_id: -1,
    movimentaEstoque: false,
    habilitaNotaFiscal: false,
    codigoBarras: "",
    peso: '',
    largura: '',
    altura: '',
    comprimento: '',
    comissao: 0,
    descricao: "",
    valorCusto: 0,
    despesasAdicionais: 0,
    outrasDespesas: 0,
    custoFinal: 0,
    estoqueMinimo: '',
    estoqueMaximo: '',
    quantidadeAtual: '',
    foto_produto: [],
    fotoPrincipal: [],
    ncm: "",
    cest: "",
    origem: "",
    pesoLiquido: '',
    pesoBruto: '',
    numeroFci: '',
    valorAproxTribut: '',
    valorPixoPis: '',
    valorFixoPisSt: '',
    valorFixoCofins: '',
    valorFixoCofinsSt: '',
    porcentagem_lucro_produto: [],
    cliente_id: {label: '', value: null},
    fornecedores_id: [{ label: '', value: null }]
  };